language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: TEST=test COVERALLS=1
      node_js: "7"
    - os: linux
      dist: trusty
      sudo: false
      env: TEST=test
      node_js: "6"

    - os: linux
      dist: trusty
      sudo: false
      env: TEST=e2e-test _FORCE_LOGS=1
      node_js: "7"
    - os: linux
      dist: trusty
      sudo: false
      env: TEST=e2e-test _FORCE_LOGS=1
      node_js: "6"

    - os: osx
      osx_image: xcode9
      env: TEST=test
      node_js: "7"
    - os: osx
      osx_image: xcode9
      env: TEST=test
      node_js: "6"

    - os: osx
      osx_image: xcode9
      env: TEST=e2e-test _FORCE_LOGS=1 PLATFORM_VERSION=11.0
      node_js: "7"
    - os: osx
      osx_image: xcode9
      env: TEST=e2e-test _FORCE_LOGS=1 PLATFORM_VERSION=11.0
      node_js: "6"
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - node --version
  - npm install
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
script:
  - npm run lint && npm run $TEST
after_success:
  - if [ -n "$COVERALLS=1" ]; then npm run coverage; fi
